--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.1.31.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 24/08/2017 09:39:48 p.m.
-- Server version: 5.7.15-log
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE `2017a202`;

--
-- Definition for table alumnos
--
DROP TABLE IF EXISTS alumnos;
CREATE TABLE alumnos (
  Legajo INT(11) NOT NULL AUTO_INCREMENT,
  NOMBRE CHAR(20) DEFAULT NULL,
  FechaNacimiento CHAR(20) NOT NULL,
  Sexo CHAR(20) DEFAULT NULL,
  PRIMARY KEY (Legajo)
)
ENGINE = INNODB
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table materias_codigo
--
DROP TABLE IF EXISTS materias_codigo;
CREATE TABLE materias_codigo (
  CodigoMateria INT(11) NOT NULL,
  Materia VARCHAR(255) NOT NULL,
  PRIMARY KEY (CodigoMateria)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table materias_cursadas
--
DROP TABLE IF EXISTS materias_cursadas;
CREATE TABLE materias_cursadas (
  Legajo INT(11) DEFAULT NULL,
  CodigoMateria INT(11) DEFAULT NULL,
  Nota DOUBLE NOT NULL,
  Activo TINYINT(1) NOT NULL,
  CONSTRAINT FK_notas_alumnos_Legajo FOREIGN KEY (Legajo)
    REFERENCES alumnos(Legajo) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_notas_materias_CodigoMateria FOREIGN KEY (CodigoMateria)
    REFERENCES materias_codigo(CodigoMateria) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

-- 
-- Dumping data for table alumnos
--
INSERT INTO alumnos VALUES
(1, 'Alfredo', '01/12/1970', 'M'),
(2, 'Gerardo', '01/10/1979', 'M'),
(3, 'Maria', '11/11/1987', 'F');

-- 
-- Dumping data for table materias_codigo
--
INSERT INTO materias_codigo VALUES
(1001, 'Analisis'),
(2001, 'Fisica_1');

-- 
-- Dumping data for table materias_cursadas
--
INSERT INTO materias_cursadas VALUES
(1, 1001, 10, 1);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;